interface DataRow {
    week: number;
    theme: string;
}

interface Data {
    [key: string]: DataRow[];
}

export const data: Data = {
    '2024': [
        { week: 1, theme: "Dreams" },
        { week: 14, theme: "Futuristic " },
        { week: 27, theme: "Sci-Fi " },
        { week: 40, theme: "Anime" },
        { week: 2, theme: "Geek " },
        { week: 15, theme: "Video Games " },
        { week: 28, theme: "Hard Surface " },
        { week: 41, theme: "Loop" },
        { week: 3, theme: "Neon " },
        { week: 16, theme: "Lost " },
        { week: 29, theme: "Vortex " },
        { week: 42, theme: "Cubes" },
        { week: 4, theme: "Robots " },
        { week: 17, theme: "Launch " },
        { week: 30, theme: "Music " },
        { week: 43, theme: "Low Poly" },
        { week: 5, theme: "Splash " },
        { week: 18, theme: "Mechanical" },
        { week: 31, theme: "Float" },
        { week: 44, theme: "Dark" },
        { week: 6, theme: "Garden " },
        { week: 19, theme: "Organic " },
        { week: 32, theme: "Radiant " },
        { week: 45, theme: "Transport" },
        { week: 7, theme: "Asymmetry " },
        { week: 20, theme: "Speed " },
        { week: 33, theme: "Weapon " },
        { week: 46, theme: "Spin" },
        { week: 8, theme: "Symetry" },
        { week: 21, theme: "Tangled " },
        { week: 34, theme: "Fragment " },
        { week: 47, theme: "High" },
        { week: 9, theme: "Junk" },
        { week: 22, theme: "Isolation" },
        { week: 35, theme: "Abstract" },
        { week: 48, theme: "Imaginary" },
        { week: 10, theme: "Illusion " },
        { week: 23, theme: "Job" },
        { week: 36, theme: "Sculpting" },
        { week: 49, theme: "Danger" },
        { week: 11, theme: "Wide Angle" },
        { week: 24, theme: "Entrance " },
        { week: 37, theme: "Wild" },
        { week: 50, theme: "Digital" },
        { week: 12, theme: "Cosmic " },
        { week: 25, theme: "Empty Spaces" },
        { week: 38, theme: "Cold " },
        { week: 51, theme: "Power" },
        { week: 13, theme: "Horror " },
        { week: 26, theme: "Mirrors " },
        { week: 39, theme: "Beasts " },
        { week: 52, theme: "Shrink" },
    ],
    '2025': [
        { week: 1, theme: "Robotic" },
        { week: 14, theme: "Cyber " },
        { week: 27, theme: "Escape " },
        { week: 40, theme: "Towers" },
        { week: 2, theme: "Cozy " },
        { week: 15, theme: "Loop " },
        { week: 28, theme: "Warriors " },
        { week: 41, theme: "Nighmare" },
        { week: 3, theme: "Organic " },
        { week: 16, theme: "Moulded " },
        { week: 29, theme: "Captured " },
        { week: 42, theme: "Sharp" },
        { week: 4, theme: "Ornamental " },
        { week: 17, theme: "Hand Crafted " },
        { week: 30, theme: "Weapons " },
        { week: 43, theme: "Music " },
        { week: 5, theme: "Sun " },
        { week: 18, theme: "Transport" },
        { week: 31, theme: "Low Poly " },
        { week: 44, theme: "Dark " },
        { week: 6, theme: "Heroes " },
        { week: 19, theme: "Devils " },
        { week: 32, theme: "Microscopic " },
        { week: 45, theme: "Illusions " },
        { week: 7, theme: "Clay " },
        { week: 20, theme: "Mysterious " },
        { week: 33, theme: "Ink " },
        { week: 46, theme: "Labyrinth " },
        { week: 8, theme: "1970's" },
        { week: 21, theme: "Science " },
        { week: 34, theme: "Food " },
        { week: 47, theme: "Lego " },
        { week: 9, theme: "Detective " },
        { week: 22, theme: "Magic " },
        { week: 35, theme: "Hologram " },
        { week: 48, theme: "Curved " },
        { week: 10, theme: "Spell " },
        { week: 23, theme: "Beasts " },
        { week: 36, theme: "Deadly Sins " },
        { week: 49, theme: "Interior " },
        { week: 11, theme: "Pokemon " },
        { week: 24, theme: "Fairy Tales " },
        { week: 37, theme: "Sport " },
        { week: 50, theme: "Weighted " },
        { week: 12, theme: "Games " },
        { week: 25, theme: "Broken " },
        { week: 38, theme: "Spin " },
        { week: 51, theme: "Expanse " },
        { week: 13, theme: "Mechanical " },
        { week: 26, theme: "Digital " },
        { week: 39, theme: "Hard Surface " },
        { week: 52, theme: "Heist " },
    ]
}